use std::fmt::Write as _;

use chipsmith_toolchain::manifest::Clock;

/// Render `[clocks]` as a Synopsys Design Constraints file for `quartus_sta`.
pub fn generate_sdc(clocks: &[Clock]) -> String {
    let mut sdc = String::from("# Generated by chipsmith\n\n");

    for clock in clocks {
        writeln!(
            sdc,
            "create_clock -name {port} -period {period:.3} [get_ports {port}]",
            port = clock.port,
            period = clock.period_ns,
        )
        .unwrap();
    }

    sdc.push_str("\nderive_clock_uncertainty\n");
    sdc
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn creates_a_clock_per_port() {
        let sdc = generate_sdc(&[
            Clock {
                port: "clk".to_string(),
                period_ns: 20.0,
            },
            Clock {
                port: "clk_125".to_string(),
                period_ns: 8.0,
            },
        ]);

        assert!(sdc.contains("create_clock -name clk -period 20.000 [get_ports clk]"));
        assert!(sdc.contains("create_clock -name clk_125 -period 8.000 [get_ports clk_125]"));
    }

    #[test]
    fn always_derives_clock_uncertainty() {
        let sdc = generate_sdc(&[Clock {
            port: "clk".to_string(),
            period_ns: 20.0,
        }]);
        assert!(sdc.contains("derive_clock_uncertainty"));
    }
}
