//! The simulator that comes with Quartus.
//!
//! ModelSim-Altera and Questa-Intel FPGA are the same tool a decade apart and
//! take the same `vlib` / `vcom` / `vsim` commands, so there is one
//! implementation and the Product says which directory it lives in.
//!
//! It lives in this crate rather than `chipsmith-sim` for one reason: its
//! binaries are vendor binaries, so they need exactly the NixOS dressing every
//! other Quartus tool gets, and that already lives here.

use std::ffi::OsString;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use chipsmith_sim::{
    SimCommands, SimFile, SimPlan, SimStep, Simulator, TestReport, TestVerdict, TestbenchRun,
};
use chipsmith_toolchain::error::ChipsmithError;
use chipsmith_toolchain::manifest::VhdlStandard;
use chipsmith_toolchain::process::{ProcessHost, ProcessSpec, RealHost};

use crate::product::{BundledSimulator, QuartusProduct};
use crate::{install, runner};

/// The library every Testbench is compiled into and elaborated from.
const WORK: &str = "work";

/// chipsmith's own settings file. It chains to the vendor's for the `std` and
/// `ieee` mappings rather than copying them, so an install that moves its
/// libraries does not leave a stale copy behind.
const INI: &str = "modelsim.ini";

/// `vcom`'s flag for a language revision.
fn vcom_std(standard: VhdlStandard) -> &'static str {
    match standard {
        VhdlStandard::Vhdl1987 => "-87",
        VhdlStandard::Vhdl1993 => "-93",
        VhdlStandard::Vhdl2008 => "-2008",
    }
}

/// The Tcl a batch-mode `vsim` runs.
///
/// `onbreak` is the whole point: with `BreakOnAssertion = 2` a failed
/// assertion breaks the simulation, and a break in batch mode otherwise just
/// drops to a prompt and eventually exits zero. Turning the break into
/// `quit -code 1` is what makes a failed Testbench a failed process.
fn vsim_script() -> String {
    [
        "onerror {quit -code 1}",
        "onbreak {quit -code 1}",
        "run -all",
        "quit -code 0",
    ]
    .join("; ")
}

/// chipsmith's `modelsim.ini`.
///
/// Two things it has to say: where the vendor's library mappings are, and that
/// a `severity error` assertion should stop the simulation. The second is the
/// default in GHDL's `--assert-level=error` and is *not* ModelSim's default
/// (which is 3, failure), so without this the same Testbench would mean
/// different things on the two Simulators.
pub fn modelsim_ini(vendor_ini: &Path) -> String {
    format!(
        "; Generated by chipsmith. Never hand-edited, never checked in.\n\
         [Library]\n\
         others = {vendor}\n\
         {WORK} = {WORK}\n\
         \n\
         [vsim]\n\
         ; 2 = error. Anything less strict and a failing assertion passes.\n\
         BreakOnAssertion = 2\n",
        vendor = vendor_ini.display(),
    )
}

pub fn vlib_args() -> Vec<OsString> {
    vec![WORK.into()]
}

pub fn vcom_args(standard: VhdlStandard, sources: &[PathBuf]) -> Vec<OsString> {
    let mut args: Vec<OsString> = vec![
        "-modelsimini".into(),
        INI.into(),
        vcom_std(standard).into(),
        "-work".into(),
        WORK.into(),
    ];
    args.extend(sources.iter().map(|s| s.as_os_str().to_owned()));
    args
}

pub fn vsim_args(testbench: &str) -> Vec<OsString> {
    vec![
        "-c".into(),
        "-modelsimini".into(),
        INI.into(),
        "-do".into(),
        vsim_script().into(),
        format!("{WORK}.{testbench}").into(),
    ]
}

/// Everything the Quartus simulator is asked to do for one run.
pub fn commands(bin_dir: &Path, vendor_ini: &Path, plan: &SimPlan) -> SimCommands {
    let tool = |name: &str| bin_dir.join(name);

    SimCommands {
        files: vec![SimFile {
            name: INI.to_string(),
            contents: modelsim_ini(vendor_ini),
        }],
        setup: vec![
            SimStep::new("Creating work library", tool("vlib"), vlib_args()),
            SimStep::new(
                format!("Compiling {} source(s)", plan.sources().len()),
                tool("vcom"),
                vcom_args(plan.standard(), plan.sources()),
            ),
        ],
        runs: plan
            .testbenches()
            .iter()
            .map(|testbench| TestbenchRun {
                testbench: testbench.clone(),
                steps: vec![SimStep::new(
                    format!("Running {testbench}"),
                    tool("vsim"),
                    vsim_args(testbench),
                )],
            })
            .collect(),
    }
}

/// A licence failure looks like any other non-zero exit, and the fix is not
/// something chipsmith can do for you — so say what it is.
const LICENSE_HINT: &str = "\nnote: this simulator needs a free node-locked licence from Altera's \
     Self-Service Licensing Center; point SALT_LICENSE_SERVER at the .dat file it sends you";

pub struct QuartusSimulator {
    product: &'static QuartusProduct,
    version: String,
    host: Arc<dyn ProcessHost>,
}

impl QuartusSimulator {
    pub fn new(product: &'static QuartusProduct, version: impl Into<String>) -> Self {
        Self::with_host(product, version, Arc::new(RealHost))
    }

    pub fn with_host(
        product: &'static QuartusProduct,
        version: impl Into<String>,
        host: Arc<dyn ProcessHost>,
    ) -> Self {
        Self {
            product,
            version: version.into(),
            host,
        }
    }

    fn simulator(&self) -> &'static BundledSimulator {
        &self.product.simulator
    }
}

#[async_trait::async_trait]
impl Simulator for QuartusSimulator {
    fn name(&self) -> &str {
        "quartus"
    }

    fn display_name(&self) -> String {
        self.simulator().display_name.to_string()
    }

    async fn test(&self, plan: &SimPlan) -> Result<TestReport, ChipsmithError> {
        // The Toolchain is the thing that carries the simulator, so asking for
        // it installs Quartus if it isn't there — the same as `build` does.
        let install_dir =
            install::ensure_installed(&*self.host, self.product, &self.version).await?;

        let simulator = self.simulator();
        let bin_dir = simulator.bin_dir(&install_dir);
        if !self.host.path_exists(&bin_dir.join("vsim")) {
            return Err(ChipsmithError::SimulatorNotFound {
                program: simulator.display_name.to_string(),
                hint: format!(
                    "{} has no simulator at {}; it is an optional component of the \
                     installer, or use `simulator = \"ghdl\"`",
                    self.product.display_name,
                    bin_dir.display()
                ),
            });
        }

        let compat = runner::host_compat(&*self.host, self.product).await?;
        let commands = commands(&bin_dir, &simulator.vendor_ini(&install_dir), plan);

        let dress = |spec: ProcessSpec| runner::for_host(spec, compat.as_ref());
        let mut report =
            chipsmith_sim::execute(&*self.host, self.name(), plan, commands, &dress).await?;
        report.simulator = self.display_name();

        if simulator.needs_license {
            for result in &mut report.results {
                if let TestVerdict::Failed { detail } = &mut result.verdict {
                    *detail = Some(format!(
                        "{}{LICENSE_HINT}",
                        detail.as_deref().unwrap_or_default()
                    ));
                }
            }
        }

        Ok(report)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn strings(args: Vec<OsString>) -> Vec<String> {
        args.into_iter()
            .map(|a| a.to_string_lossy().into_owned())
            .collect()
    }

    #[test]
    fn the_manifests_vhdl_standard_reaches_vcom() {
        for (standard, flag) in [
            (VhdlStandard::Vhdl1987, "-87"),
            (VhdlStandard::Vhdl1993, "-93"),
            (VhdlStandard::Vhdl2008, "-2008"),
        ] {
            assert!(strings(vcom_args(standard, &[])).contains(&flag.to_string()));
        }
    }

    #[test]
    fn compilation_reads_every_source_in_the_order_it_was_given() {
        let sources = vec![
            PathBuf::from("/p/src/blinky.vhd"),
            PathBuf::from("/p/tb/blinky_tb.vhd"),
        ];
        let args = strings(vcom_args(VhdlStandard::Vhdl2008, &sources));
        assert_eq!(
            &args[args.len() - 2..],
            ["/p/src/blinky.vhd", "/p/tb/blinky_tb.vhd"]
        );
    }

    /// Without `onbreak`, a broken assertion drops vsim to a prompt and the
    /// process still exits zero — the test would silently pass.
    #[test]
    fn a_broken_assertion_quits_with_a_failing_code() {
        let script = vsim_script();
        assert!(script.contains("onbreak {quit -code 1}"), "{script}");
        assert!(script.contains("onerror {quit -code 1}"), "{script}");
        assert!(script.contains("run -all"), "{script}");
    }

    #[test]
    fn a_run_is_batch_mode_and_names_the_testbench_in_the_work_library() {
        let args = strings(vsim_args("blinky_tb"));
        assert!(args.contains(&"-c".to_string()), "{args:?}");
        assert_eq!(args.last().unwrap(), "work.blinky_tb");
    }

    /// ModelSim breaks at `failure` by default and GHDL is told to break at
    /// `error`. Without this line the same Testbench means two things.
    #[test]
    fn the_generated_ini_breaks_on_the_same_severity_ghdl_does() {
        let ini = modelsim_ini(Path::new("/q/questa_fse/modelsim.ini"));
        assert!(ini.contains("BreakOnAssertion = 2"), "{ini}");
        assert!(ini.contains("others = /q/questa_fse/modelsim.ini"), "{ini}");
        assert!(ini.contains("work = work"), "{ini}");
    }

    /// Every invocation has to read chipsmith's ini, or the severity setting
    /// and the work mapping are both silently ignored.
    #[test]
    fn every_tool_that_reads_settings_is_pointed_at_the_generated_ini() {
        for args in [
            strings(vcom_args(VhdlStandard::Vhdl2008, &[])),
            strings(vsim_args("tb")),
        ] {
            let at = args.iter().position(|a| a == "-modelsimini").expect("ini");
            assert_eq!(args[at + 1], "modelsim.ini", "{args:?}");
        }
    }

    #[test]
    fn the_bundled_simulator_is_found_next_to_the_toolchain() {
        let simulator = BundledSimulator {
            subdir: "questa_fse",
            display_name: "Questa",
            needs_license: true,
        };
        let install = Path::new("/home/u/intelFPGA_lite/23.1std");
        assert_eq!(
            simulator.bin_dir(install),
            Path::new("/home/u/intelFPGA_lite/23.1std/questa_fse/bin")
        );
        assert_eq!(
            simulator.vendor_ini(install),
            Path::new("/home/u/intelFPGA_lite/23.1std/questa_fse/modelsim.ini")
        );
    }
}
